AWSTemplateFormatVersion: 2010-09-09

Metadata:

  License: Apache-2.0

Description: >-

  AWS CloudFormation Template EC2, that uses an already created key-pair and a

  volume EBS.

Parameters:

  KeyName:

    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance

    Type: 'AWS::EC2::KeyPair::KeyName'

    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:

  EC2Instance:

    Type: 'AWS::EC2::Instance'

    Properties:

      InstanceType: t2.medium

      SecurityGroups:

        - !Ref InstanceSecurityGroup

      KeyName: !Ref KeyName

      ImageId: ami-0fe472d8a85bc7b0e

  EBSVolume:

    Type: 'AWS::EC2::Volume'

    Properties:

      Size: 8

      VolumeType: gp2

      AvailabilityZone: us-east-1a

  EBSVolumeAttachment:

    Type: 'AWS::EC2::VolumeAttachment'

    Properties:

      InstanceId: !Ref EC2Instance

      VolumeId: !Ref EBSVolume

      Device: /dev/sdb

  InstanceSecurityGroup:

    Type: 'AWS::EC2::SecurityGroup'

    Properties:

      GroupDescription: Enable SSH access via port 22

      SecurityGroupIngress:

        - IpProtocol: tcp

          FromPort: 22

          ToPort: 22

          CidrIp: 0.0.0.0/0

Outputs:

  InstanceId:

    Description: InstanceId of the newly created EC2 instance

    Value: !Ref EC2Instance

  AZ:

    Description: Availability Zone of the newly created EC2 instance

    Value: !GetAtt

      - EC2Instance

      - AvailabilityZone

  PublicDNS:

    Description: Public DNSName of the newly created EC2 instance

    Value: !GetAtt

      - EC2Instance

      - PublicDnsName

  PublicIP:

    Description: Public IP address of the newly created EC2 instance

    Value: !GetAtt

      - EC2Instance

      - PublicIp
